### ISSUE TITLE
Unable to set cartographic position while creating tileset.json

### ISSUE THREAD

**Issue by lllllleo42** [CesiumGS/3d-tiles-tools#110]
I want to create a tileset.json from a given set of glb files, but I get an error called "Unknown arguments: cartographicPositionDegrees, 31.206812371430992, 0". How could I solve this problem?
<img width="724" alt="c6bc2a8390bb45c18b796c71ff90983" src="https://github.com/CesiumGS/3d-tiles-tools/assets/122014332/e0a28978-f2a1-45b3-829c-88edebca8917">

**Comment by javagl** [comment]
It looks like you are using a version of the `3d-tiles-tools` that you installed from NPM. This version does not yet include the functionality to set the `cartographicPositionDegrees`, because this functionality was only added a few days ago.

If you want to use this function, you can use the current state of the repository, as described in the [Developer Setup](https://github.com/CesiumGS/3d-tiles-tools?tab=readme-ov-file#developer-setup) : Clone the repository, run `npm install`, and then run the tools with `npx ts-node .\src\cli\main.ts createTilesetJson ...`.

If this does not work, just drop a note here.

(A new release of the 3D Tiles Tools, which _includes_ the extended functionality, will be released to NPM soon)

**Comment by lllllleo42** [comment]
Thank you very much！It really helped me a lot. ~\(≥▽≤)/~

**Comment by javagl** [comment]
The extended functionality will be part of the next release, so I assume that this is not an issue and can be closed.
