### ISSUE TITLE
Documentation for noobs on NPM?

### ISSUE THREAD

**Issue by EddyNCNL** [CesiumGS/3d-tiles-tools#35]
Hi,

I found your tool when searching for ways to convert .b3dm into .gltf.
Apparently it needs some other piece of software called NPM?

Can you perhaps add just some introduction on what is actually needed to run your tool?
E.g. what is this NPM and where do I get it? That would help a noob like me a lot.

Thanks.

**Comment by javagl** [comment]
npm (and Node.js) are the standard tools that are required when developing and running applications in JavaScript (or TypeScript). 

Roughly: 
- Node.js is the "execution environment" or "the runtime" that actually executes the JavaScript
- npm (the "Node.js Package Manager") is used for installing packages and their dependencies

Maybe you already do have it installed? 
What happens when you run
`npm -v`
at the console? 

If you don't already have it: We could replicate some of the existing documentation for installing Node.js and npm in the documentation of the `3d-tiles-tools`. But I think that it makes more sense to just point to https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#overview here.

If there are specific questions, just add them here.

**Comment by javagl** [comment]
If you had a chance to try it out (or have specific hints about what might be added to the README, beyond a link to the NPM installation instructions), just drop a note here. Otherwise, I'd close this issue soon.

**Comment by EddyNCNL** [comment]
Hey there,

Sorry, I don't have the time to try it out now, but I will somewhere upcoming weeks. I'll have a look at your comment.
Thanks.

**Comment by javagl** [comment]
For now, I don't see any further actionable items here. If there are specific questions, feel free to reopen.
