### ISSUE TITLE
How to generate tileset.json

### ISSUE THREAD

**Issue by linglom1** [CesiumGS/3d-tiles-tools#47]
When I am using the command line to convert .gltf models to .b3dm, it does not generate a tileset.json file. How can I generate a tileset.json file?

**Comment by javagl** [comment]
There currently is no functionality for generating a `tileset.json` file for glTF models.

(Note that with 3D Tiles 1.1, you don't have to convert the glTF asset to B3DM any more. You can use glTF directly as the tile content). 

However, it would be relatively easy to create such a functionality, and we'll consider to implement this in the near future.

There are some degrees of freedom for how "powerful" this functionality should be. If the goal is only to create a minimal `tileset.json` for a _single_ glTF asset, then the structure of this `tileset.json` would be simple:
```
{
  "asset" : {
    "version" : "1.1"
  },
  "geometricError" : 1.0,
  "root" : {
    "boundingVolume" : {
      "box" : [ 0.5, 0.5, 1.0, 0.5, 0.0, 0.0, 0.0, -0.5, 0.0, 0.0, 0.0, 1.0 ]
    },
    "geometricError" : 0.0,
    "refine" : "REPLACE",
    "content" : {
      "uri" : "content.glb"
    }
  }
}
```
The main purpose of offering the creation of such a JSON file as part of the tools would be to **compute the proper bounding box**. In the example above, the bounding box is just a unit cube. In order to define the bounding box so that it matches the one of the glTF file, one could use a function similar to [this example in the `BoundingBoxTests` sample](https://github.com/CesiumGS/3d-tiles-samples/tree/main/1.1/BoundingBoxTests#conversion) to compute the tileset bounding box from the glTF bounding box.

(If the goal is only to do this once, then you could obtain the bounding box of the glTF with https://gltf.report/ and use this function to compute the bounding box that has to be put into the `tileset.json`)

**Comment by linglom1** [comment]
Thank you very much for your response. My idea is to convert an FBX model into multiple GLTF models, and then generate a suitable tileset.json. I am really looking forward to the arrival of the function to automatically generate tileset.json. Finally, I wish you a happy life.

**Comment by javagl** [comment]
> into multiple GLTF models, and then generate a suitable tileset.json

That's the main reason why I mentioned the _"degrees of freedom for how "powerful" this functionality should be"_ (and emphasized that such a function would be simple if it should only be applied to **one** glTF file). When there are _multiple_ glTF assets, then one has to take into account that each of these models may have to be displayed at a different position - meaning that the proper `transform` matrices must be inserted into the tile hierarchy. Additionally, one of the main purposes of 3D Tiles is usually to offer a Hierarchical Level of Detail (HLOD), and this would raise the question: Which glTF asset does represent which level of detail? 

Conversely, if the glTF assets already _are_ at the right positions, and there is no level of detail, and they should just be combined into a single tileset, then the functionality should be simple. And of course, if we implement it as part of the tools, it will probably roughly (!) something that takes a _list_ of glTF assets (or maybe all assets in one directory), and generates a Tileset JSON that just combines all of them, without translations, in one level.

**Comment by linglom1** [comment]
Greetings! May I inquire about the expected release date for this feature? Recently, I have been attempting to autonomously generate tileset.json files from multiple .glb files. However, during the generation process, I encountered some difficulties in accurately setting the values for geometricError and boundingVolume.box. I am unsure if the values I generated are correct, hence my eagerness for the release of this feature.

**Comment by javagl** [comment]
There currently is no timeline for that, because it is not a feature that is _planned_ to be implemented. But I occasionally would have found that functionality useful myself, and in its most simple form, it should not be toooo much effort to implement, so I'll give this a try in the next days, and maybe open a Draft PR for first tests and feedback soon.

**Comment by javagl** [comment]
@linglom1 I created a **DRAFT** PR with this functionality at https://github.com/CesiumGS/3d-tiles-tools/pull/51 . Maybe you want to have a look and try it out, and see whether it works for you or whether you have any suggestions. It's really only a draft for now, so there may be glitches, but in principle, it should be possible get this into a reasonable shape quickly.

**Comment by linglom1** [comment]
Hello, when I ran the command "npx ts-node ./src/main.ts createTilesetJson -i C:/test/glb -o C:/test/tileset.json", I received the following prompt: "Usage: npx 3d-tiles-tools <command> [options]" and "Unknown arguments: i, o, createTilesetJson". It seems that the project is unable to recognize this command.

**Comment by javagl** [comment]
Note that the PR has not been merged yet. So in order to try it you, you explicitly have to check out the branch that the PR is based on, which is https://github.com/CesiumGS/3d-tiles-tools/tree/tileset-json-creation 

At the command line, that would probably be something like
(`git fetch --all`)
`git checkout origin/tileset-json-creation`

**Comment by linglom1** [comment]
Greetings! In the tileset.json generated by the 3d-tiles-tools-tileset-json-creation project, all child nodes are currently assigned a geometricError value of 1. Would it be possible to enhance this by dynamically setting the geometricError based on the diagonal size of the glb model?

**Comment by javagl** [comment]
There is some vagueness in what the "geometric error" actually _is_. The most general description could be that it quantifies the degree of simplification. Therefore, leaf tiles usually have a geometric error of 0 (or 1), because they are _the most detailed representation that exists_.

Assigning a value that is based on the diagonal of the GLB bounding box would be possible. But then you might have a model with a diagonal length of 10, and another one with a length of 1, and ... people might wonder why only one of them (namely, the one with the diagonal length of 10) is displayed...

**Comment by sweco-sekrsv** [comment]
Hi!

When I run createTilesetJson on my files I don't get correct boundingboxes, it's rotated somehow. See image below and the attached zip-file.

![bug](https://github.com/CesiumGS/3d-tiles-tools/assets/10772529/3949aeba-8d19-4da9-ad12-6c6d865b6087)
[bound_bug.zip](https://github.com/CesiumGS/3d-tiles-tools/files/12380554/bound_bug.zip)

**Comment by javagl** [comment]
These bounding boxes are not wrong. They are axis-aligned bounding boxes. In theory, the `tileset.boundingVolume.box` could have any orientation. There is no reason why these bounding boxes should, for example, be ~"aligned with the surface of the earth at the given location". This is probably what you expected. And I agree that it would look .... prettier. But the bounding boxes are only required to enclose the whole geometry, and that's what they are doing. 

You are right insofar that it would be desirable to compute a bounding box that is **as small as possible**. And in your screenshot, it is clear that the bounding boxes could be _much_ smaller if they had a different orientation. But until now, the `createTilesetJson` command does not claim to do this. 

Computing the minimum oriented bounding box would be possible, but, .... not perfectly trivial in all cases. One approach could be to compute the actual vertex positions of the geometry and then use [`OrientedBoundingBox.fromPoints`](https://cesium.com/learn/cesiumjs/ref-doc/OrientedBoundingBox.html#.fromPoints).

I'll leave this as a note here, and consider it to be implemented as part of https://github.com/CesiumGS/3d-tiles-tools/pull/51 .

**Comment by javagl** [comment]
To wrap this up:

@linglom1 
> In the tileset.json generated by the 3d-tiles-tools-tileset-json-creation project, all child nodes are currently assigned a geometricError value of 1. Would it be possible to enhance this by dynamically setting the geometricError based on the diagonal size of the glb model?

I actually had increased the default values here (to ~512), because otherwise, the error was deemed to be so low that it was not  rendered e.g. when zooming out a bit too far in CesiumJS. There's still no sensible "rule" for assigning the geometric error here, but using a higher value probably makes sense.

Beyond that, I assume that the functionality that was added in https://github.com/CesiumGS/3d-tiles-tools/pull/51 (and will be part of the next release) sufficiently addresses the original goal here for now. 

@sweco-sekrsv

Although these bounding volumes are "technically correct" (which is the best kind of 'correct'), they should indeed be smaller and better fitting the contents. There is no _really_ easy solution for that, but it is now tracked in https://github.com/CesiumGS/3d-tiles-tools/issues/58 , and maybe we can compute better bounding volumes in the future.
