### ISSUE TITLE
To-do list for upgrade command

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles-tools#5]
Tentative changes for `1.0` that should be handled in the `upgrade` command

* Move batch table hierarchy to extension: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/303
* Fix leading slash: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/issues/141
* CESIUM_RTC to RTC_CENTER: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/issues/142
* `asset.gltfUpAxis` removed
* Padding: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/225
* gltf 1.0 to 2.0
* content.url changed to content.uri
* Upgrade glTF semantic `BATCHID` to `_BATCHID`

Progress is in https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/2.0-tools

**Comment by javagl** [comment]
This issue originally referred to the upgrade from "pre-1.0" to "1.0" tilesets. Some of the bullet points have therefore been addressed already, or are tracked in dedicated issues, or have become obsolete (the latter also insofar that `gltf-pipeline` does the actual upgrade of glTF data). 

The question of the _scope_ of the `upgrade` command is still relevant, though, and maybe now more than before, because it may now refer to upgrading 3D Tiles 1.0 to 1.1.

There is a (somewhat preliminary) set of [options in the `TilesetUpgrader` class](https://github.com/CesiumGS/3d-tiles-tools/blob/4bf71d2b5a1651787f851971422fe168aa26780e/src/tilesetProcessing/TilesetUpgrader.ts#L26) that show what the upgrade is _currently_ doing, and this includes some of the bullet points from above.

Beyond that, one could consider to extend the `upgrade` functionality to cover more of what is described in the [3D Tiles 1.0 to 1.1 migration guide for tile formats](https://github.com/CesiumGS/3d-tiles/blob/7b364caf1b22708e3e49d1ae814c3cd8518d278a/specification/TileFormats/glTF/MIGRATION.adoc).

**Comment by javagl** [comment]
<sup>(This comment contains some `TODO`s - I'll edit and extend this as we move on...)</sup>

The [migration guide](https://github.com/CesiumGS/3d-tiles/blob/7b364caf1b22708e3e49d1ae814c3cd8518d278a/specification/TileFormats/glTF/MIGRATION.adoc) gives a few hints about how to "emulate" several features of the previous tile formats in glTF. I'll try to start sorting out which of these steps could be part of an automated process.

On the highest level, the entry point would be to add this functionality to the `TilesetUpgrader`. It should be possible to enable/disable the upgrade based on the input type, so there would probably be `upgradeB3dmToGlb`, `upgradeI3dmToGlb`, and `upgradePntsToGlb` flags in the [`UpgradeOptions` in the `TilesetUpgrader`](https://github.com/CesiumGS/3d-tiles-tools/blob/9f0f16bb945117f200b0781011df8c6fddd86d1f/src/tilesetProcessing/TilesetUpgrader.ts#L34).

(The case of CMPT is special in many ways, and has to be discussed separately)

The actual upgrade functionality would then be implemented in the `TilesetUpgrader`. This upgrade will include modifications to the tileset JSON. These modifications will at least be things like changing the `content.uri` from `.b3dm` to `.glb`. But it may be even more, for example, when converting a (single-content) `.cmpt` into a (multiple-contents) list of `.glb` contents. 

(The latter has some constraints, though. It may not be done for _implicit_ tile content, for example....)

A large part of the infrastructure for this kind of modification already exists. For example, the `b3dmToGlb` functionality that is currently part of the [pipeline content stages](https://github.com/CesiumGS/3d-tiles-tools/blob/9f0f16bb945117f200b0781011df8c6fddd86d1f/src/pipelines/ContentStageExecutor.ts#L188) could also be applied to do more than just _extracting_ the GLB from the B3DM. So on this level, many migration steps can be boiled down to the seemingly trivial core:

*"The migration function receives a B3DM/PNTS/I3DM buffer. It creates an equivalent GLB buffer"*

<sup>And what "equivalent" means, is sorted out in the following sections</sup>

---

###  Feature detection and error handling

A large part of the features from the legacy tile formats _can_ be migrated automatically. In the first versions, there will be some  things that are _not_ migrated _yet_, but will be migrated in future versions. But there also are cases that can "never" be migrated automatically. One overarching question is how to handle that. A high-level, straightforward approach could be to examine the input data and its Feature Table and Batch Table, and if it contains _anything_ that can _not_ be migrated, then just print a warning and leave the content unmodified.

---

### The `RTC_CENTER` 

For all tile formats, the migration guide says

> The `RTC_CENTER` can be added to the translation component of the root node of the glTF asset.

There already is a function for replacing the `CESIUM_RTC` extension in a glTF with such a node transform (in [`GtlfUtilities`](https://github.com/CesiumGS/3d-tiles-tools/blob/9f0f16bb945117f200b0781011df8c6fddd86d1f/src/contentProcessing/GtlfUtilities.ts#L164)). Extending that to be a function like `applyRootTransform(gltf, center)` would be trivial, and then it could be made part of the `upgrade` command. Whatever the input tile format is: We'd parse the Batch Table JSON, extract the `RTC_CENTER`, and pass it to that function.

### The BATCH_ID

This applies to all tile formats as well. The actual ID can be translated into the `EXT_mesh_features` extension. This should not be much more than translating the `_BATCHID` into a `_FEATURE_ID_0` attribute 🤞 

Translating the _contents_ of the Batch Table into glTF may be a bit more tricky. Broadly speaking, it would involve translating the current Batch Table JSON information - specifically, the "binary body references" - into a 3D Metadata representation, and the Batch Table binary data into property attributes, so that they can be represented with the [`EXT_structural_metadata`](https://github.com/KhronosGroup/glTF/blob/756893d30d02b22f54ddef08aafa9d2e98de145d/extensions/2.0/Vendor/EXT_structural_metadata/README.md) extension.

It should be possible to implement that somewhat generically, juggling only with JSON and buffers, and I don't foresee any "large" technical hurdles here - roughly speaking: `EXT_structural_metadata` is more powerful/expressive than the Batch Table, so it should be possible to convert everything without losing information.


### PNTS to GLB

This could be easy for most cases, and impossible for others. Looking at the [point semantics](https://github.com/CesiumGS/3d-tiles/blob/7b364caf1b22708e3e49d1ae814c3cd8518d278a/specification/TileFormats/PointCloud/README.adoc#point-semantics):

- POSITION, NORMAL: Standard glTF attributes
- RGBA, RGB: Standard glTF attributes with `VEC4` or `VEC3`
- POSITION_QUANTIZED, RGB565, NORMAL_OCT16P: Not possible. This would cause a warning, and leave the data unmodified
- CONSTANT_RGBA (global): Could be emulated with a standard glTF material

The fact that this is relatively clearly separated into "easy" and "impossible" makes it a good candidate for a first step. Different test cases for point clouds that contain these features can be found via https://github.com/CesiumGS/cesium/blob/db2669aae149e965a3578fd0343384a33f83543c/Specs/Scene/PointCloud3DTileContentSpec.js#L35-L70

### B3DM to GLB

TODO

### I3DM to GLB

TODO

### CMPT to GLB

TODO

**Comment by javagl** [comment]
Just to have a back-link here: There are some points about a possible upgrade from 3D Tiles 1.0 to 1.1 summarized in https://github.com/CesiumGS/3d-tiles/issues/592#issuecomment-982634526 that may have to be taken into account here.

**Comment by javagl** [comment]
A short update: Most of the functionality for the generalized upgrade has been implemented in https://github.com/CesiumGS/3d-tiles-tools/pull/41 and https://github.com/CesiumGS/3d-tiles-tools/pull/52 . 

The remaining (open) task is that of upgrading CMPT files. There are some caveats (as described in detail in the previous comment), so this may not be tackled immediately. But the approach of "merging the (resulting) GLBs" could be worth a try, because for the kind of data that _usually_ appears as tile content, this could be implementable with glTF-Transform with reasonable effort.

**Comment by javagl** [comment]
A small update: The conversion of CMPT to GLB has been implemented as part of https://github.com/CesiumGS/3d-tiles-tools/pull/117 (with caveats, corner cases, and limitations laid out in the PR, and the comment above)

Now, from the list that was posted when we were still young, there are two main points left:

- https://github.com/CesiumGS/3d-tiles-tools/issues/7 - what to do with that?
- "Padding"

The latter made its way into the specification, But it was pretty late, and caused some "disruption" like https://github.com/CesiumGS/cesium/commit/4b3b4186b4afa2307d7d1666569826d864b984ca and many (other) ("legacy") data sets that are "invalid" due to some alignment errors.

_Some_ of this is already handled via the functionality of converting the "legacy" tile formats to GLB. But one could make a case for offering a command that just takes contents like B3DM and fixes the alignment requirements, _with as few other changes as possible_. Maybe this should be tracked in a dedicated issue...?

**Comment by lilleyse** [comment]
@javagl I think this issue is closeable now, after 6 years 😄 

> But one could make a case for offering a command that just takes contents like B3DM and fixes the alignment requirements, with as few other changes as possible. Maybe this should be tracked in a dedicated issue...?

Feel free to open a separate issue. Though this would be lower priority.
