### ISSUE TITLE
Convert command should check for tileset.json or rename a supplied .json file

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/3d-tiles-tools#53]
When using the convert command to convert a 3d tiles file based dataset to a .3dtiles database, the convert command should check either:

a) A tileset.json exists in the supplied folder before converting
b) If the user supplies a specific path a to a tilesets json (eg. example.json) it should rename to tileset.json on conversion

Otherwise, the user is able to generate a .3dtiles dataset that does not include a tileset.json.  When uploaded to hosting services such as Cesium ion, this tileset is not able to be used as the expectation is a tileset.json is present.

**Comment by javagl** [comment]
When the input directory contains a `tileset.json` and a `mainTileset.json`, and the user gives `directory/mainTileset.json` as the input, then the `mainTileset.json` can **not** be renamed to `tileset.json`. 

That sounds like an unlikely case, but people can create new tilesets with the `merge` command, and that might well result in a "top-level" tileset JSON that is called `mergedTileset.json`. That one may _refer_ to the `tileset.json`, directly or indirectly, so it's not possible to simply rename that `tileset.json` either.

My gut feeling is that this is still unlikely enough to warrant an error message. Unfortunately, there would hardly be a way for the user to deal with this situation. A workaround - iff this case ever comes up - could be to "wrap" the tileset into another one, so that the structure of

`/directory/mainTileset.json`
`/directory/tileset.json`

would become

`/directory/tileset.json` (the top-level one that refers to `subdirectory/mainTileset.json` as an "external" one)
`/directory/subdirectory/mainTileset.json`
`/directory/subdirectory/tileset.json`

**Comment by javagl** [comment]
I created a PR for addressing this.

The behavior for these cases that are addressed with this PR is summarized here:

There is a `basic` input (directory or ZIP file). It contains a `tileset.json` and a `tilesetA.json`. The conversions for the basic case:

- `basic/` to `basic.3tz`: Works. There is a `tileset.json` in the input
- `basic/tileset.json` to `basic.3tz`: Works. 
- `basic/tilesetA.json` to `output/resultTilesetA.json`: Works. (The `tileset.json` does not matter here)
- `basic/tilesetA.json` to `basic.3tz`: **Fails**. The `tilesetA.json` has to be renamed to `tileset.json` to be written into the 3TZ file, causing a duplicate with the other `tileset.json`
- `basic.zip` to `output/`: Works. This is just unpacking the ZIP.
- `basic.zip` to `output/result.json`: **Fails**. It is not clear which of the JSON files in the input should become the `result.json`. (One could use the `tileset.json` from the ZIP and write it as `result.json` here...)

There is an `ambiguous` input (directory or ZIP file). It contains a `tilesetA.json` and a `tilesetB.json`. The conversions for the ambiguous case:

- `ambiguous/` to `ambiguous.3tz`: **Fails**. It is not clear which of the JSON files in the input should become the `tileset.json` file
- `ambiguous/tilesetA.json` to `ambiguous .3tz`: Works. The specified input file will become the `tileset.json`
- `ambiguous.zip` to `output/`: Works. This is just unpacking the ZIP.
- `ambiguous.zip` to `output/tileset.json`: **Fails**. It is not clear which of the JSON files in the input should become the `tileset.json`
- `ambiguous.zip` to `ambiguous.3tz`: **Fails**. It is not clear which of the JSON files in the input should become the `tileset.json`
